In [ ]:
# list  : element data type 可以各自不同
# numpy : element data type 必須一致
scores = [44, 55, 66, 77, '88']
scores

[44, 55, 66, 77, '88']

In [ ]:
# list  : element data type 可以各自不同
# numpy : element data type 必須一致
import numpy as np
scores2 = np.array([44, 55, 66, 77, 88])
# array 向量 矩陣
scores2

array([44, 55, 66, 77, 88])

In [ ]:
list(range(-5, 5, 1))
# range 不含最後一個數字

[-5, -4, -3, -2, -1, 0, 1, 2, 3, 4]

In [ ]:
import numpy as np
np.arange(-5, 5, 0.2)[:13]
# [:13] 前13筆資料

array([-5. , -4.8, -4.6, -4.4, -4.2, -4. , -3.8, -3.6, -3.4, -3.2, -3. ,
       -2.8, -2.6])

In [ ]:
# 考你一個題目
#  如果要產生 0, 2, 4, 6 的數值
# 請用 range, np.arange方式生成 np.linspace
print( list( range(0, 8, 2) ) )
print( np.arange(0, 8, 2) )
print(np.linspace(0, 6, 4)) # linspace 含頭含尾

[0, 2, 4, 6]
[0 2 4 6]


array([0., 2., 4., 6.])

In [ ]:
# 轉換資料型態 pandas.2-rank --> numpy --> list
# 請問以下的數據怎樣轉換成 list
data = np.arange(0, 8, 2)
print(data, type(data)) # numpy
print(data.tolist()) # list

[0 2 4 6] <class 'numpy.ndarray'>
[0, 2, 4, 6]


In [ ]:
import numpy as np
test1 = [0, 2, 4, 6]
test2 = np.array(test1)
print(test1)
print(test2)



[0, 2, 4, 6]
[0 2 4 6]


In [ ]:
test1 + 10 # list

TypeError: can only concatenate list (not "int") to list

In [ ]:
test2 + 10 # numpy (batch process)

array([10, 12, 14, 16])