In [ ]:
# list  : element data type 可以各自不同
# numpy : element data type 必須一致
# boolean slicing <------------------------
import numpy as np
student = np.array([10, 20, 30, 40, 50])
scores2 = np.array([44, 55, 66, 77, 88])
# 請問 怎樣取得 20 <=student <=40, # 避開使用迴圈
filter = (student >= 20) & (student <=40)
print(filter)
scores2[filter]

[False  True  True  True False]


array([55, 66, 77])

In [2]:
import numpy as np
student = np.array([10, 20, 30, 40, 50])
scores2 = np.array([44, 55, 66, 77, 88])
# 請問 怎樣取得 20 <=student <=40
scores2[ (student >= 20) & (student <=40) ] #取代回圈
# {}字 ()動作 [] numpy/list

array([55, 66, 77])

In [3]:
# 考 請問 如何取得前三位同學 學號 與 對應成績
student[:3], scores2[:3]

(array([10, 20, 30]), array([44, 55, 66]))

In [6]:
# 哪些人score<60
student[scores2<60]

array([10, 20])

In [7]:
# 請問如何將 以下數據 變化成 pandas.DataFrame
# student scores
#   10   44
#   20   55
#   ..   ..
import pandas as pd
import numpy as np
student = np.array([10, 20, 30, 40, 50])
scores2 = np.array([44, 55, 66, 77, 88])
sample = pd.DataFrame({'student': student, 'scores': scores2})
sample

student  scores
0       10      44
1       20      55
2       30      66
3       40      77
4       50      88

In [8]:
# 請問怎樣找sample 的 0, 1, 2 學生 編號 & 分數
sample[:3]

student  scores
0       10      44
1       20      55
2       30      66

In [9]:
sample.iloc[[1, 3, 4],  :]

student  scores
1       20      55
3       40      77
4       50      88

In [11]:
# 從 sample 中的 scores 欄位判斷 大於等於 60分以上者 的 student編號是多少
# 輸出 DataFrame
#     student .. scores
#
sample[ sample['scores'] >= 60 ]

student  scores
2       30      66
3       40      77
4       50      88